# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: ""
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# SEO settings
title: Dev Together
description: "Connecting people starting their development career with technical mentors through low-commitment, high-value, human interactions"
keywords: "meetup, development, coding, mentorship"

# Site settings
url: http://github.com/mercedesb/dev-together
baseurl: "/"
headernav:
  -
    title: Our Approach
    url: "/approach/"
  -
    title: Chapters
    url: "/chapters/"
  -
    title: Sponsorship
    url: "/sponsorship/"
  -
    title: Blog
    url: "/blog/"
  -
    title: Code of Conduct
    url: "/code-of-conduct/"

# Author settings
author:
  name      : Mercedes Bernard
  thumb     : /images/author.jpg
  email     : devtogetherchi@gmail.com
  twitter   : http://twitter.com/devtogetherchi
  instagram : http://instagram.com/devtogetherchi
  meetup    : http://meetup.com/devtogetherchi
  eventtime : Tues, Sept 11, 6pm
  eventlink : http://bit.ly/devtogethersept2018

# google_analytics: UA-52446115-1
repo: http://github.com/mercedesb/dev-together
